version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  up:
    cmds:
      - migrate -path ./migration -database "postgres://postgres:12345@localhost:5436/task_db?sslmode=disable" up

  down:
    cmds:
      - migrate -path ./migration -database "postgres://postgres:12345@localhost:5436/task_db?sslmode=disable" down
  run:
    cmds:
      - go run cmd/main.go